### ISSUE TITLE
pattern assets/Acme-Regular.ttf: no matching files found

### ISSUE THREAD

**Issue by stt106** [oddstream/gosol#1]
I just cloned the project and tried to build it locally but got this error: `pattern assets/Acme-Regular.ttf: no matching files found`. Is there a missing assets folder under `schriftbank` folder?

**Comment by stt106** [comment]
It seems that `ttf` files are ignored as shown in `.gitignore`

**Comment by oddstream** [comment]
Updated .gitignore to include .ttf assets
